import { afterEach, describe, expect, it } from "vitest";
import { resolve } from "node:path";
import { WorkerSupervisor } from "../src/providers/supervisor.js";
const supervisors: WorkerSupervisor[] = [];
const init = { model_id: "test", task: "transcription", provider: "fake", device: "cpu", options: {} };
afterEach(async () => { await Promise.all(supervisors.splice(0).map((item) => item.stop())); });
describe("worker supervisor", () => {
  it("warms with structured provider options and a configurable deadline", async () => { const supervisor = new WorkerSupervisor("python3", [resolve("tests/fixtures/fake_worker.py")], 100, 500, { ...init, options: { prefix: "initialized ", warmup_delay: 0.02 } }); supervisors.push(supervisor); await supervisor.start(); expect(supervisor.ready).toBe(true); const request = await supervisor.request({ task: "transcription", path: "/tmp/x" }, new AbortController().signal); const messages = []; for await (const message of request.messages()) messages.push(message); expect(messages).toEqual(expect.arrayContaining([expect.objectContaining({ type: "result", text: "initialized test transcript" }), expect.objectContaining({ type: "done" })])); });
  it("rejects a warmup that exceeds its configured deadline and schedules restart", async () => { const supervisor = new WorkerSupervisor("python3", [resolve("tests/fixtures/fake_worker.py")], 100, 10, { ...init, options: { warmup_delay: 0.1 } }); supervisors.push(supervisor); await expect(supervisor.start()).rejects.toThrow("Worker warmup timed out"); expect(supervisor.restartCount).toBeGreaterThan(0); });
  it("schedules restart when the worker process cannot spawn", async () => { const supervisor = new WorkerSupervisor("/definitely/missing/python", [resolve("tests/fixtures/fake_worker.py")], 100, 100, init); supervisors.push(supervisor); await expect(supervisor.start()).rejects.toThrow(/ENOENT/); expect(supervisor.state).toBe("failed"); expect(supervisor.restartCount).toBeGreaterThan(0); });
  it("kills and restarts a worker that misses its cancellation deadline", async () => {
    const supervisor = new WorkerSupervisor("python3", [resolve("tests/fixtures/fake_worker.py")], 50, 1000, init);
    supervisors.push(supervisor);
    await supervisor.start();
    const controller = new AbortController();
    const request = await supervisor.request({ task: "speech", input: "uncancellable", format: "pcm" }, controller.signal);
    const collecting = (async () => { for await (const _message of request.messages()) { /* consume */ } })();
    await new Promise((resolveDelay) => setTimeout(resolveDelay, 20));
    controller.abort();
    await expect(collecting).rejects.toThrow("Worker exited");
    for (let attempt = 0; attempt < 30 && !supervisor.ready; attempt++) await new Promise((resolveDelay) => setTimeout(resolveDelay, 50));
    expect(supervisor.ready).toBe(true);
    expect(supervisor.restartCount).toBeGreaterThan(0);
  });
  it("survives a cancellation write racing a worker crash and stays stopped", async () => {
    const supervisor = new WorkerSupervisor("python3", [resolve("tests/fixtures/fake_worker.py")], 50, 1000, init);
    supervisors.push(supervisor);
    await supervisor.start();
    const controller = new AbortController();
    const request = await supervisor.request({ task: "speech", input: "crash", format: "pcm" }, controller.signal);
    const iterator = request.messages()[Symbol.asyncIterator]();
    await expect(iterator.next()).resolves.toMatchObject({ value: { type: "chunk" } });
    controller.abort();
    await expect(iterator.next()).rejects.toBeInstanceOf(Error);
    for (let attempt = 0; attempt < 20 && supervisor.restartCount === 0; attempt++) await new Promise((resolveDelay) => setTimeout(resolveDelay, 10));
    expect(supervisor.restartCount).toBeGreaterThan(0);
    await supervisor.stop();
    await new Promise((resolveDelay) => setTimeout(resolveDelay, 600));
    expect(supervisor.ready).toBe(false);
    expect(supervisor.state).toBe("stopped");
  });
  it("keeps the worker usable after a buffered message iterator is abandoned", async () => {
    const supervisor = new WorkerSupervisor("python3", [resolve("tests/fixtures/fake_worker.py")], 100, 1000, init);
    supervisors.push(supervisor);
    await supervisor.start();
    const request = await supervisor.request({ task: "speech", input: "large", format: "pcm" }, new AbortController().signal);
    const iterator = request.messages()[Symbol.asyncIterator]();
    await expect(iterator.next()).resolves.toMatchObject({ value: { type: "chunk" } });
    await new Promise((resolveDelay) => setTimeout(resolveDelay, 100));
    await iterator.return?.();
    request.cancel();
    await request.done;
    const followup = await supervisor.request({ task: "transcription", path: "/tmp/x" }, new AbortController().signal);
    const messages = [];
    for await (const message of followup.messages()) messages.push(message);
    expect(messages).toEqual(expect.arrayContaining([expect.objectContaining({ type: "result", text: "test transcript" }), expect.objectContaining({ type: "done" })]));
    expect(supervisor.restartCount).toBe(0);
  });
});
